[project]
name = "py-photos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.7.0",
    "imageio>=2.25.0",
    "pillow>=10.0.0",
    "python-dotenv>=1.0.0",
    "rawpy>=0.18.0",
]
